Refactor GitHub Actions workflow for Hugo site build and testing
- Removed the base URL specification from the build step to allow for more flexible deployments.
- Added a new step to list the contents of the public directory and its subdirectory, enhancing visibility into the build output.
- Updated ignore settings to exclude the "/3DPrintingAdventures/" path from HTTPS enforcement.

diff --git a/.github/workflows/build-and-test.yaml b/.github/workflows/build-and-test.yaml
--- a/.github/workflows/build-and-test.yaml
+++ b/.github/workflows/build-and-test.yaml
@@ -25,7 +25,7 @@ jobs:
           extended: true
 
       - name: Build
-        run: hugo --minify --baseURL https://joshuarlowry.github.io/3DPrintingAdventures/
+        run: hugo --minify
 
       - name: Upload build artifact
         uses: actions/upload-artifact@v3
@@ -65,6 +65,7 @@ jobs:
           EnforceHTTPS: true
           IgnoreURLs:
             - "mailto:"
+            - "/3DPrintingAdventures/"
           IgnoreDirs:
             - "public/images"
           IgnoreAltMissing: true
@@ -74,6 +75,13 @@ jobs:
           ExternalTimeout: 60
           LogLevel: 2
           EOF
+
+      - name: List files in public
+        run: |
+          echo "Contents of public directory:"
+          ls -la public/
+          echo "\nContents of public/docs directory:"
+          ls -la public/docs || echo "docs directory not found"
 
       - name: Run HTML Tests
         run: |
